# Generated by Django 4.2.11 on 2024-06-10 20:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("cart_app", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="cart",
            old_name="season_id",
            new_name="session_id",
        ),
    ]
