# Generated by Django 4.2.11 on 2024-06-08 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("course_app", "0006_course_slug"),
    ]

    operations = [
        migrations.AlterField(
            model_name="course",
            name="thumbnail",
            field=models.ImageField(
                blank=True, null=True, upload_to="course_thumbnails"
            ),
        ),
    ]
