# Generated by Django 4.2.11 on 2024-06-10 12:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("course_app", "0007_alter_course_thumbnail"),
    ]

    operations = [
        migrations.AlterField(
            model_name="course",
            name="language",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="language_courses",
                to="course_app.language",
            ),
        ),
    ]
