# Generated by Django 4.2.11 on 2024-06-10 19:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("course_app", "0008_alter_course_language"),
    ]

    operations = [
        migrations.CreateModel(
            name="Enrollment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("purchased_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="Prerequisite",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=75)),
            ],
        ),
        migrations.AlterField(
            model_name="course",
            name="title",
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name="lecture",
            name="title",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="season",
            name="title",
            field=models.CharField(max_length=100),
        ),
        migrations.DeleteModel(
            name="Requirements",
        ),
        migrations.AddField(
            model_name="prerequisite",
            name="course",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="course_prerequisite",
                to="course_app.course",
            ),
        ),
        migrations.AddField(
            model_name="enrollment",
            name="course",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="user_courses",
                to="course_app.course",
            ),
        ),
        migrations.AddField(
            model_name="enrollment",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="user_courses",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
