# Generated by Django 4.2.11 on 2024-06-11 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("course_app", "0010_review"),
    ]

    operations = [
        migrations.AlterField(
            model_name="review",
            name="rating",
            field=models.IntegerField(
                blank=True, choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], null=True
            ),
        ),
    ]
