# Generated by Django 4.2.11 on 2024-06-11 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("course_app", "0011_alter_review_rating"),
    ]

    operations = [
        migrations.AddField(
            model_name="enrollment",
            name="purchased_price",
            field=models.DecimalField(
                blank=True, decimal_places=3, max_digits=10, null=True
            ),
        ),
    ]
