# Generated by Django 4.2.11 on 2024-06-11 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("course_app", "0014_alter_lecture_duration"),
    ]

    operations = [
        migrations.CreateModel(
            name="Subtitle",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name="course",
            name="costly",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="course",
            name="level",
            field=models.CharField(
                blank=True,
                choices=[
                    ("All Levels", "All Levels"),
                    ("Beginner", "Beginner"),
                    ("Intermediate", "Intermediate"),
                    ("Advanced", "Advanced"),
                ],
                max_length=20,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="course",
            name="subtitles",
            field=models.ManyToManyField(
                blank=True, null=True, to="course_app.subtitle"
            ),
        ),
    ]
