# Generated by Django 4.2.11 on 2024-06-11 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("course_app", "0018_alter_course_price"),
    ]

    operations = [
        migrations.AlterField(
            model_name="lecture",
            name="file",
            field=models.FileField(upload_to="courses/files/videos"),
        ),
    ]
