# Generated by Django 4.2.11 on 2024-06-14 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("course_app", "0019_alter_lecture_file"),
    ]

    operations = [
        migrations.AlterField(
            model_name="course",
            name="updated_at",
            field=models.DateField(auto_now=True),
        ),
    ]
