# Generated by Django 4.2.11 on 2024-06-11 08:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("cart_app", "0003_coupon_order_orderitem"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="coupon",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="coupon_used",
                to="cart_app.coupon",
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="coupon_used",
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name="order",
            name="subtotal",
            field=models.DecimalField(
                blank=True, decimal_places=3, max_digits=10, null=True
            ),
        ),
    ]
