# Generated by Django 4.2.11 on 2024-06-16 18:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("cart_app", "0004_alter_order_coupon_alter_order_coupon_used_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="cart",
            name="coupon",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="user_coupon",
                to="cart_app.coupon",
            ),
        ),
        migrations.AddField(
            model_name="cart",
            name="coupon_is_used",
            field=models.BooleanField(default=False),
        ),
    ]
