# Generated by Django 4.2.11 on 2024-06-07 09:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("course_app", "0004_alter_course_category"),
    ]

    operations = [
        migrations.RenameField(
            model_name="course",
            old_name="Language",
            new_name="language",
        ),
    ]
