# Generated by Django 4.2.11 on 2024-06-11 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("course_app", "0013_lecture_duration"),
    ]

    operations = [
        migrations.AlterField(
            model_name="lecture",
            name="duration",
            field=models.FloatField(default=0),
        ),
    ]
